### ISSUE TITLE
'URL using bad/illegal format or missing URL' when sending FHIR requests

### ISSUE THREAD

**Issue by karzideh** [POLAR-fhiR/fhircrackr#110]
When using the fhircrackr as mentioned in the Readme.md, the following error message is returned:

`Fehler in curl::curl_fetch_memory(url, handle = handle) : 
  URL using bad/illegal format or missing URL`

We use an own in-house developed FHIR-server and it seems that the fhircrackr doesn't get along with our pagination-method.

**Comment by palmjulia** [comment]
Hi! That's an interesting error! Could you quickly check for me if the error occurs if you set `max_bundles=1` in `fhir_search()`?

**Comment by tobiasgirardet** [comment]
Yes, there is a next link in each bundle. Here is an example:

```json
  "link": [
    {
      "relation": "self",
      "url": "/app/FHIR/r4/Patient?_shipPagination=eyJvZmZzZXQiOjB9"
    },
    {
      "relation": "first",
      "url": "/app/FHIR/r4/Patient?_shipPagination=eyJvZmZzZXQiOjB9"
    },
    {
      "relation": "next",
      "url": "/app/FHIR/r4/Patient?_shipPagination=eyJvZmZzZXQiOjIwfQ%3D%3D"
    }
  ],
```

**Comment by karzideh** [comment]
If I set `max_bundles=1` the error is not thrown.

**Comment by palmjulia** [comment]
Okay thanks then it is indeed the next link that is causing problems with curl. I'll look into it and get back to you.

**Comment by karzideh** [comment]
Thanks!

**Comment by palmjulia** [comment]
Okay, so if I understand it correctly you next link is not an actual URL but just a part of it that would supposedly have to be pasted to the base url of your FHIR server? So any programme that wants to page through the bundle has to know the base url *and* the next link to get to the next bundle?

**Comment by palmjulia** [comment]
Oh that's unfortunate. Because we currently don't have a way to know the base url for sure inside of `fhir_search()`, because we're allowing any FHIR Search URL to be handed over to the function and I think there is no 100% exact way to extract (only) the base url from an arbitrary FHIR search request.

I don't suppose the base URL is per se is to be found anywhere in your searchset bundle right? So we'd probably have to create an additional argument or some kind of extension to the existing arguments that allow you to pass the base url to `fhir_search` so we can internally add it the next link before querying the next bundle.

**Comment by karzideh** [comment]
Our base-url doesn't contain any single `/` so it should work. I checked the regex with our next-links and the base-url is extracted correctly. Thanks for the quick fix!

**Comment by palmjulia** [comment]
Thank's for checking. It's not a fix yet, we'll have to incorporate it into the `fhircrackr` so you can use it. But I think we should be able to squeeze it in before the next release (which is just around the corner). I'm out of office this week but I'll give you an update as soon as I integrated the fix in the development version so you can try it out.

**Comment by palmjulia** [comment]
Yes, definetely. As usual a couple of other things came in the way, but I hope I'll be fixing it in the next few days and ask you to test the fix before we're putting it on CRAN. Thanks for offering!

**Comment by palmjulia** [comment]
Finally got around to it. Seems almost too easy, not sure if I forgot anything but can't test it because I don't have a server with relative next links. Could you check if `fhir_search()` now works when you install the the github version with:
`remotes::install_github("https://github.com/POLAR-fhiR/fhircrackr", ref = "fix_paging")`?
